project:
  type: website
  render:
    - "*.md"
    - README.md
    - toolbox/README.md
    - standards/README.md

website:
  title: "Open Portal"
  navbar:
    left:
      - href: toolbox/README.md
        text: Toolbox
      - href: https://open-models.org
        text: Knowledge Base
      - href: https://university.open-models.org
        text: Open University

    tools:
      - icon: github
        href: https://github.com/Open-Models/Portal
      - icon: chat-right-dots
        href: https://github.com/Open-Models/Portal/discussions
      - icon: cc-circle
        href: https://creativecommons.org/publicdomain/zero/1.0/

format:
  html:
    theme: cosmo
    toc: true
